import { useEffect, useState } from 'react'
import Head from 'next/head'

import { Title, Container, Center, Text } from '@mantine/core'

import DropdownSelect from '../components/DropdownSelect'
import { ApiResponse, FuelEconomyApiValue } from '../shared/interfaces'

export default function Home() {
  const [years, updateYears] = useState([] as FuelEconomyApiValue[]);
  const [selectedYear, updateSelectedYear] = useState<string | null>(null)
  
  useEffect(() => {
    getYears()
  },[])

  async function getYears() {
    const years: ApiResponse<FuelEconomyApiValue[]> = await (await fetch('http://localhost:3000/api/vehicle/years')).json()
  
    updateYears(years.result as FuelEconomyApiValue[])
  }



  return (
    <div>
      <Head>
        <title>CarBon - Vehicle Carbon Calculator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Container mt='md'>
          <Center>
            <Title order={1}>Welcome to CarBon!</Title>
          </Center>
        </Container>

        <Container mt='md' size='xs' px='xs'>
          <Center>
            <Text>
              Enter your vehicle information (year, make, model, trim) the distance of your commute (one way), and the number of days you make the commute.
            </Text>
          </Center>
        </Container>

        <Container mt='md' size='xs'>
          <DropdownSelect
            label='Select Vehicle Year'
            placeholder='Year'
            data={years}
            value={selectedYear}
            updateStateFn={updateSelectedYear}
          />
        </Container>

      </main>

      {/* <footer>
        Footer
      </footer> */}
    </div>
  )
}
